### PR TITLE
feat(lang): add German language

### PR DESCRIPTION
**Pull request by dev-inside**
i18n: German added

### CODE REVIEW

**Comment by Zoobdude** [comment]
Great 👍

**Comment by dev-inside** [comment]
So, I'd deleted the other branch I'd created accidentally and updated the i18n provider. This branch should be up-to-date. Sorry, was my first experience with PR via Github.

**Comment by Zoobdude** [comment]
No worries

**Comment by Zoobdude** [comment]
Could you also re-name the PR to `feat(lang): add German language`

**Comment by dev-inside** [comment]
Dun 👍

**Pull request closed without merging**
