### PR TITLE
docs: Normalize doc theme to match app design

### LINKED ISSUE #75: [docs] Normalize doc theme to match app design
- [ ] Use the same [tabler icons](https://icones.js.org/collection/tabler) as the app
- [ ] Normalize colors

### PR DESCRIPTION
**Pull request by Zoobdude**
image

image

Closes #75

### CODE REVIEW

**Comment by CorentinTh** [comment]
Thank you for the PR! 🙏
Everythings looks good regarding the code :ok_hand: 

After checking out the screenshots, I feel like I might prefer the version with the more contrasted background for the left navigation sidebar. However, I'm still undecided on whether I like it better fully aligned with the rest of the app or if I prefer keeping that slight distinction. 

What do you think ?

**Comment by Zoobdude** [comment]
I thought about this as I edited it and tried it with and without the contrasting side bar, but decided I did quite like the entirely consistent theme.

**Comment by CorentinTh** [comment]
Just to let you know @Zoobdude, I re-enabled the aside backgrounds (+ code blocks background) but adapted the colors to the app secondary colors in #175

**Comment by Zoobdude** [comment]
Thanks for the update :)

**Pull request merged**
