### PR TITLE
fix(layout) Adjust new note button on mobile

### PR DESCRIPTION
**Pull request by Zoobdude**
Currently on mobile devices the nav bar is pretty full:
image

I was thinking how to make this slightly tidier, and tried hiding the text:
image

@CorentinTh  Any suggestions of a better way to do this or would you rather just keep it with the text?

### CODE REVIEW

**Comment by CorentinTh** [comment]
Thanks for addressing this point!
I was considering grouping all the icons (GitHub, i18n, etc.) inside the 3-dots [dropdown menu](https://shadcn-solid.com/docs/components/dropdown-menu) when on small screen (perhaps we could replace it with a "hamburger" icon when they are grouped? I dunno)

But we can also replace the creation button with an icon

**Comment by Zoobdude** [comment]
Good idea! I'll work on this over the weekend.

**Comment by Zoobdude** [comment]
Not sure what SonarCloud is complaining about? Is this okay to ignore or shoud I use className instead?

**Comment by CorentinTh** [comment]
Yeah you may ignore the `className` stuff, it's an issue on sobnacloud side, it interprets the jsx as react and not solid, I'm marking them as false positive, I need to dig the config to exclude this rule

**Comment by Zoobdude** [comment]
Hope you're happy with the way I've implemented it, let me know if there's any revisions you would like me to make.

**Review by CorentinTh — CHANGES_REQUESTED** [review]
Thanks for the pr, it's what I add in mind 💪

Before merging can you 
- remove the empty keys from other languages, since when a key is missing (not empty) it'll fallback to the default language 
- keep the text in the button in mobile, since all the icons are gone on mobile, we have the needed room to keep it with text 

Thanks again 🙏

**Review by CorentinTh — APPROVED** [review]
Great, thank you 🙏

**Pull request merged**
